#!/usr/bin/env node
/**
 * Web-based installer for n8n-library.
 * Run: node setup.js
 * Then open http://localhost:3100/setup in your browser.
 */
const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const app = express();
app.use(express.json());

const PORT = process.env.SETUP_PORT || 3100;
const ENV_PATH = path.join(__dirname, '.env');

// Serve setup page
app.get('/', (_req, res) => res.redirect('/setup'));

app.get('/setup', (_req, res) => {
  res.send(SETUP_HTML);
});

// Test database connection
app.post('/setup/test-db', async (req, res) => {
  const { Pool } = require('pg');
  const { host, port, user, password, database, schema } = req.body;
  const pool = new Pool({ host, port: parseInt(port, 10) || 5432, user, password, database, connectionTimeoutMillis: 5000 });
  try {
    const client = await pool.connect();
    if (schema && schema !== 'public') {
      await client.query(`CREATE SCHEMA IF NOT EXISTS "${schema}"`);
      await client.query(`SET search_path TO "${schema}"`);
    }
    await client.query('SELECT 1');
    client.release();
    await pool.end();
    res.json({ ok: true });
  } catch (err) {
    try { await pool.end(); } catch {}
    res.json({ ok: false, error: err.message });
  }
});

// Run full install
app.post('/setup/install', async (req, res) => {
  const c = req.body;
  try {
    // 1. Generate session secret
    const sessionSecret = crypto.randomBytes(32).toString('hex');

    // 2. Build .env content
    let env = '';
    env += `# Generated by n8n-library setup wizard on ${new Date().toISOString()}\n\n`;
    env += `# Database\n`;
    env += `DB_POSTGRESDB_HOST=${c.db_host}\n`;
    env += `DB_POSTGRESDB_PORT=${c.db_port || 5432}\n`;
    env += `DB_POSTGRESDB_USER=${c.db_user}\n`;
    env += `DB_POSTGRESDB_PASSWORD=${c.db_password || ''}\n`;
    env += `DB_POSTGRESDB_DATABASE=${c.db_database}\n`;
    env += `DB_POSTGRESDB_SCHEMA=${c.db_schema || 'public'}\n`;
    env += `\n# Application\n`;
    env += `PORT=${c.app_port || 3100}\n`;
    env += `SESSION_SECRET=${sessionSecret}\n`;
    env += `APP_URL=${c.app_url || 'http://localhost:3100'}\n`;
    if (c.node_env) env += `NODE_ENV=${c.node_env}\n`;
    env += `\n# n8n Instance\n`;
    env += `N8N_INTERNAL_URL=${c.n8n_url || ''}\n`;
    env += `N8N_API_KEY=${c.n8n_api_key || ''}\n`;
    if (c.smtp_host) {
      env += `\n# Email (SMTP)\n`;
      env += `SMTP_HOST=${c.smtp_host}\n`;
      env += `SMTP_PORT=${c.smtp_port || 25}\n`;
      if (c.smtp_user) env += `SMTP_USER=${c.smtp_user}\n`;
      if (c.smtp_pass) env += `SMTP_PASS=${c.smtp_pass}\n`;
      if (c.smtp_from) env += `SMTP_FROM=${c.smtp_from}\n`;
    }
    env += '\n';

    // 3. Write .env
    fs.writeFileSync(ENV_PATH, env, 'utf8');

    // 4. Set env vars for this process so migrate.js can use them
    process.env.DB_POSTGRESDB_HOST = c.db_host;
    process.env.DB_POSTGRESDB_PORT = String(c.db_port || 5432);
    process.env.DB_POSTGRESDB_USER = c.db_user;
    process.env.DB_POSTGRESDB_PASSWORD = c.db_password || '';
    process.env.DB_POSTGRESDB_DATABASE = c.db_database;
    process.env.DB_POSTGRESDB_SCHEMA = c.db_schema || 'public';
    process.env.SESSION_SECRET = sessionSecret;
    process.env.N8N_INTERNAL_URL = c.n8n_url || '';
    process.env.N8N_API_KEY = c.n8n_api_key || '';

    // 5. Run migration
    const { execSync } = require('child_process');
    const migrateOutput = execSync('node migrate.js', {
      cwd: __dirname,
      env: { ...process.env },
      timeout: 30000,
    }).toString();

    // 6. Create admin user if custom credentials provided
    if (c.admin_email && c.admin_password) {
      const { Pool } = require('pg');
      const bcrypt = require('bcryptjs');
      const pool = new Pool({
        host: c.db_host,
        port: parseInt(c.db_port, 10) || 5432,
        user: c.db_user,
        password: c.db_password || '',
        database: c.db_database,
      });
      const schema = c.db_schema || 'public';
      const client = await pool.connect();
      if (schema !== 'public') await client.query(`SET search_path TO "${schema}"`);

      // Update the default admin user created by migrate.js
      const hash = await bcrypt.hash(c.admin_password, 10);
      await client.query(
        `UPDATE users SET email = $1, username = $2, password_hash = $3 WHERE role = 'admin' AND id = (SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1)`,
        [c.admin_email, c.admin_username || c.admin_email.split('@')[0], hash]
      );
      client.release();
      await pool.end();
    }

    res.json({
      ok: true,
      message: 'Installation complete!',
      migrate: migrateOutput.trim(),
      nextSteps: `Stop this setup server and start the app:\n  node server.js\n\nThen open ${c.app_url || 'http://localhost:3100'} in your browser.`,
    });
  } catch (err) {
    res.json({ ok: false, error: err.message, stack: err.stack });
  }
});

app.listen(PORT, () => {
  console.log(`\n  n8n-library Setup Wizard`);
  console.log(`  Open http://localhost:${PORT}/setup in your browser\n`);
});

// --- Inline HTML for the setup wizard ---
const SETUP_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>n8n Library — Setup</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f1f5f9; color: #1e293b; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
  .setup { max-width: 640px; width: 100%; }
  .setup-header { text-align: center; margin-bottom: 32px; }
  .setup-header h1 { font-size: 28px; font-weight: 700; margin-bottom: 6px; }
  .setup-header p { color: #64748b; font-size: 14px; }
  .setup-logo { font-size: 48px; margin-bottom: 12px; }
  .card { background: #fff; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); padding: 24px; margin-bottom: 16px; }
  .card h2 { font-size: 16px; font-weight: 600; margin-bottom: 4px; display: flex; align-items: center; gap: 8px; }
  .card h2 .step { background: #ff6d5a; color: #fff; width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 700; flex-shrink: 0; }
  .card p.desc { font-size: 12px; color: #94a3b8; margin-bottom: 16px; }
  .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 12px; }
  .form-row.full { grid-template-columns: 1fr; }
  .form-group { display: flex; flex-direction: column; gap: 4px; }
  .form-group label { font-size: 12px; font-weight: 600; color: #475569; text-transform: uppercase; letter-spacing: 0.5px; }
  .form-group input, .form-group select { padding: 8px 12px; border: 1px solid #e2e8f0; border-radius: 8px; font-size: 14px; outline: none; transition: border-color 0.2s; }
  .form-group input:focus, .form-group select:focus { border-color: #ff6d5a; }
  .form-group .hint { font-size: 11px; color: #94a3b8; }
  .btn { padding: 10px 20px; border: none; border-radius: 8px; font-size: 14px; font-weight: 600; cursor: pointer; transition: all 0.2s; display: inline-flex; align-items: center; gap: 8px; }
  .btn-primary { background: #ff6d5a; color: #fff; }
  .btn-primary:hover { background: #e0523f; }
  .btn-primary:disabled { background: #cbd5e1; cursor: not-allowed; }
  .btn-secondary { background: #f1f5f9; color: #475569; border: 1px solid #e2e8f0; }
  .btn-secondary:hover { background: #e2e8f0; }
  .btn-row { display: flex; gap: 10px; justify-content: flex-end; margin-top: 8px; }
  .status { padding: 10px 14px; border-radius: 8px; font-size: 13px; margin-top: 12px; display: none; }
  .status.success { display: block; background: #f0fdf4; color: #166534; border: 1px solid #bbf7d0; }
  .status.error { display: block; background: #fef2f2; color: #991b1b; border: 1px solid #fecaca; }
  .status.info { display: block; background: #eff6ff; color: #1e40af; border: 1px solid #bfdbfe; }
  .result-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-top: 16px; display: none; }
  .result-box h3 { font-size: 15px; margin-bottom: 8px; color: #166534; }
  .result-box pre { font-size: 13px; background: #1e293b; color: #e2e8f0; padding: 12px; border-radius: 6px; overflow-x: auto; white-space: pre-wrap; }
  .optional-badge { font-size: 10px; background: #f1f5f9; color: #94a3b8; padding: 2px 6px; border-radius: 4px; font-weight: 500; }
  .spinner { display: inline-block; width: 16px; height: 16px; border: 2px solid #fff; border-top-color: transparent; border-radius: 50%; animation: spin 0.6s linear infinite; }
  @keyframes spin { to { transform: rotate(360deg); } }
  @media (max-width: 600px) { .form-row { grid-template-columns: 1fr; } }
</style>
</head>
<body>
<div class="setup">
  <div class="setup-header">
    <div class="setup-logo">&#9881;</div>
    <h1>n8n Library Setup</h1>
    <p>Configure your installation in a few steps</p>
  </div>

  <!-- Step 1: Database -->
  <div class="card">
    <h2><span class="step">1</span> Database</h2>
    <p class="desc">PostgreSQL connection details. The database must already exist.</p>
    <div class="form-row">
      <div class="form-group"><label>Host</label><input type="text" id="db_host" value="localhost"></div>
      <div class="form-group"><label>Port</label><input type="number" id="db_port" value="5432"></div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>User</label><input type="text" id="db_user" value="postgres"></div>
      <div class="form-group"><label>Password</label><input type="password" id="db_password" value=""></div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>Database</label><input type="text" id="db_database" value="n8n_library"></div>
      <div class="form-group"><label>Schema</label><input type="text" id="db_schema" value="public"><div class="hint">Use a custom schema to share a database</div></div>
    </div>
    <div class="btn-row">
      <button class="btn btn-secondary" onclick="testDb()">Test Connection</button>
    </div>
    <div class="status" id="dbStatus"></div>
  </div>

  <!-- Step 2: Admin Account -->
  <div class="card">
    <h2><span class="step">2</span> Admin Account</h2>
    <p class="desc">Credentials for the initial admin user</p>
    <div class="form-row">
      <div class="form-group"><label>Username</label><input type="text" id="admin_username" value="admin"></div>
      <div class="form-group"><label>Email</label><input type="email" id="admin_email" placeholder="admin@example.com"></div>
    </div>
    <div class="form-row full">
      <div class="form-group"><label>Password</label><input type="password" id="admin_password" placeholder="Choose a strong password"><div class="hint">Minimum 6 characters</div></div>
    </div>
  </div>

  <!-- Step 3: Application -->
  <div class="card">
    <h2><span class="step">3</span> Application</h2>
    <p class="desc">How the application will be accessed</p>
    <div class="form-row">
      <div class="form-group"><label>Port</label><input type="number" id="app_port" value="3100"></div>
      <div class="form-group"><label>Environment</label>
        <select id="node_env"><option value="">Development</option><option value="production">Production</option></select>
      </div>
    </div>
    <div class="form-row full">
      <div class="form-group"><label>Application URL</label><input type="text" id="app_url" placeholder="https://library.example.com" value="http://localhost:3100"><div class="hint">Public URL users will access. Used in emails and links.</div></div>
    </div>
  </div>

  <!-- Step 4: n8n Instance -->
  <div class="card">
    <h2><span class="step">4</span> n8n Instance <span class="optional-badge">OPTIONAL</span></h2>
    <p class="desc">Connect your default n8n instance. You can add more later in Settings.</p>
    <div class="form-row full">
      <div class="form-group"><label>n8n Internal URL</label><input type="text" id="n8n_url" placeholder="http://localhost:5678"><div class="hint">URL the server uses to reach n8n (Docker service name or IP)</div></div>
    </div>
    <div class="form-row full">
      <div class="form-group"><label>n8n API Key</label><input type="password" id="n8n_api_key" placeholder="n8n API key"><div class="hint">Generate in n8n: Settings > API > Create API Key</div></div>
    </div>
  </div>

  <!-- Step 5: Email -->
  <div class="card">
    <h2><span class="step">5</span> Email (SMTP) <span class="optional-badge">OPTIONAL</span></h2>
    <p class="desc">For password resets and daily summary emails</p>
    <div class="form-row">
      <div class="form-group"><label>SMTP Host</label><input type="text" id="smtp_host" placeholder="smtp.example.com"></div>
      <div class="form-group"><label>SMTP Port</label><input type="number" id="smtp_port" value="25"></div>
    </div>
    <div class="form-row">
      <div class="form-group"><label>SMTP User</label><input type="text" id="smtp_user" placeholder="Optional"></div>
      <div class="form-group"><label>SMTP Password</label><input type="password" id="smtp_pass" placeholder="Optional"></div>
    </div>
    <div class="form-row full">
      <div class="form-group"><label>From Address</label><input type="email" id="smtp_from" placeholder="noreply@example.com"></div>
    </div>
  </div>

  <!-- Install -->
  <div class="card" style="text-align:center">
    <button class="btn btn-primary" id="installBtn" onclick="runInstall()" style="width:100%;justify-content:center;padding:14px;font-size:16px">
      Install n8n Library
    </button>
    <div class="status" id="installStatus"></div>
    <div class="result-box" id="installResult">
      <h3>Installation Complete</h3>
      <pre id="installOutput"></pre>
    </div>
  </div>
</div>

<script>
function val(id) { return document.getElementById(id).value.trim(); }
function showStatus(elId, type, msg) {
  var el = document.getElementById(elId);
  el.className = 'status ' + type;
  el.textContent = msg;
  el.style.display = 'block';
}

async function testDb() {
  showStatus('dbStatus', 'info', 'Testing connection...');
  try {
    var res = await fetch('/setup/test-db', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        host: val('db_host'), port: val('db_port'), user: val('db_user'),
        password: val('db_password'), database: val('db_database'), schema: val('db_schema'),
      }),
    });
    var data = await res.json();
    if (data.ok) showStatus('dbStatus', 'success', 'Connection successful!');
    else showStatus('dbStatus', 'error', 'Connection failed: ' + data.error);
  } catch (e) {
    showStatus('dbStatus', 'error', 'Request failed: ' + e.message);
  }
}

async function runInstall() {
  var email = val('admin_email');
  var pw = val('admin_password');
  if (!email) return showStatus('installStatus', 'error', 'Admin email is required');
  if (!pw || pw.length < 6) return showStatus('installStatus', 'error', 'Admin password must be at least 6 characters');
  if (!val('db_host') || !val('db_database')) return showStatus('installStatus', 'error', 'Database host and name are required');

  var btn = document.getElementById('installBtn');
  btn.disabled = true;
  btn.innerHTML = '<span class="spinner"></span> Installing...';
  showStatus('installStatus', 'info', 'Running installation...');
  document.getElementById('installResult').style.display = 'none';

  try {
    var res = await fetch('/setup/install', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        db_host: val('db_host'), db_port: val('db_port'), db_user: val('db_user'),
        db_password: val('db_password'), db_database: val('db_database'), db_schema: val('db_schema'),
        admin_username: val('admin_username'), admin_email: email, admin_password: pw,
        app_port: val('app_port'), app_url: val('app_url'), node_env: val('node_env'),
        n8n_url: val('n8n_url'), n8n_api_key: val('n8n_api_key'),
        smtp_host: val('smtp_host'), smtp_port: val('smtp_port'),
        smtp_user: val('smtp_user'), smtp_pass: val('smtp_pass'), smtp_from: val('smtp_from'),
      }),
    });
    var data = await res.json();
    if (data.ok) {
      showStatus('installStatus', 'success', data.message);
      var result = document.getElementById('installResult');
      result.style.display = 'block';
      document.getElementById('installOutput').textContent =
        (data.migrate ? data.migrate + '\\n\\n' : '') + data.nextSteps;
      btn.innerHTML = 'Installed';
    } else {
      showStatus('installStatus', 'error', 'Installation failed: ' + data.error);
      btn.disabled = false;
      btn.innerHTML = 'Retry Installation';
    }
  } catch (e) {
    showStatus('installStatus', 'error', 'Request failed: ' + e.message);
    btn.disabled = false;
    btn.innerHTML = 'Retry Installation';
  }
}
</script>
</body>
</html>`;
